[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = "0.4.3"
clap = { version = "3.2.17", features = ["derive"] }
reqwest = { version = "0.11.11", features = [
    "blocking",
    "rustls-tls"
], default-features = false }
rustc-hash = "1.1.0"
